name: contact_info
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_slidable: ^2.0.0
  geolocator: ^9.0.2
  go_router: ^6.0.0
  http: ^0.13.5
  intl: ^0.17.0
  reactive_forms: ^10.6.8
  sqflite: ^2.2.2
  url_launcher: ^6.1.7

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
